version: '3.8'

services:
  kafka:
    image: bashj79/kafka-kraft
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/opt/kafka/kafka-logs
  mongodb_filter:
    container_name: turkcell-filterdb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_filter_data:/data/db
  mongodb_invoice:
    container_name: turkcell-invoicedb
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongodb_invoice_data:/data/db
  mysql:
    image: mysql
    container_name: maintenancedb-t1
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=maintenancedb-t1
      - MYSQL_USER=mysql
      - MYSQL_TCP_PORT=3307
      - VIRTUAL_PORT=3307
    ports:
      - '3307:3307'
    expose:
      - 3307
    volumes:
      - mysqldb_data:/data/db
volumes:
  kafka_data:
  mongodb_filter_data:
  mongodb_invoice_data:
  mysqldb_data: