spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        default-label: master
        git:
          uri: https://github.com/MertKayatay/Gelecegi-yazanlar-rentacar-microservice-config
server:
  port: 8888